apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:k5GlV6d9IW6B2cC5NuCwtF5zEzP6sPgB7LROcRbiPfB5jsHN,iv:99IAllERZX/R1i0eUK0EnvvIYylTuRdrovJt0GleeIk=,tag:KC7dEJNFyfVTrHprxIdJ6Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:tJUXT0p/lwIwVSTGXhNZDLKsAUk/omaIzacSKEQcHN8rWfnsBaE8S59h0Vu5DPxY4pZ0paYCA3364k34E1lsf3s25pP25zaIJI8MmUPYuXXuNr360xCKY4tjQhtOY9D5OuP982mNhWLIaVfv1BJoX2lXzU78I9kfwXOp/Vm7eVQ7tMVLzeiFQc+130zaHN6/YqV2LSzCiZRkCVGE9KsS0Jf5oC/KRXbCBeVaEaxw5w==,iv:67gciiiiurq4HhdJCjZQ8U4fQCAfMysbIZWPlok/Hq0=,tag:bwKxuqFpYW9BZkMhUt22GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xghpya6xsfw8lzplcc95dauvmz66x8388n528chxw5w69rg0wv8sde73ac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRmYrNS9LdWN0S3F2d0tF
            SXZMMHdCZ0NXalBydjNscUV2Rk0vSXZxOWk4CkdPT0d0SkFiWEphNUpsaDRlekhj
            YS90NTdVUkFIdW9vQWJqUjFsa3dxOVUKLS0tIHJ1aHl6M0xNOHJmTXpZSGtaWlNT
            RElNYk1BNWNNVGVhS2NMZkFad0JCU28KNq1MBXE1RDMtMZQrxMT1P1lsbRa/sWVx
            eLXhITp5Pd/ZyGD4CCZ3mRkjtNdy+z21dtwwiUDiu6R2p6dUljFZWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T16:51:42Z"
    mac: ENC[AES256_GCM,data:hD36pzOc6ZRVw9dPDQ6Z1VwItAmZuzBgGP7sh3tmACQEZKWamETD9Jj/QhCwyYVRFKi5NNpifHfx5rTWfDPNPzdp0Hk7T6Q3KeWMbKBiQ4JhJvoTKLos73fgzlGxSVaDhqjWRfd/IgCzQSTZsTTgFxJ3UCra+6lcZrrDQ3xDimo=,iv:Xtg3rUe1nXWwQRUoTIckogCF4cMr64YvxMviCqxCqis=,tag:5jv5U42St3A8+/EdfEZhew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
