apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9Gnglq9q2DvzKqPV3LFXkD8wFK27LI9IGYU0XdI1p6nu6h8i,iv:OMvKR82OP43XYOu7Ex9R6XbsxzpZ5KPKwnKqkaoQUfk=,tag:/Djv3WV6NnwxYiRYCy3Cng==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:8p5pLRTmJopVe3aTTL+pKTB4HxYeYaATNBfQ3lQ1GxCD20mwbZzC29TQ/0UHsETu1/miiKk6XmyHba1s+rngxCYMeYC9U8XkQydOJn1tDvj6aEAO9c1KNJteey3UwkVkUBr65hTzdPcdtV10E5KyYmFbCHOl0h6WD6UZpCsrYHsQ/11lBi4nzFkDC8apakqpLHyaDY0kv3DfVGWzo3LVjTsBz/CtxiTmu4BMW3SyqQ==,iv:bsGl5p1g2djhHG4FOdLoWKSfGDneZWrv24oqc2uDtLI=,tag:uvsOOEIxv+Q9cC4e5xgdNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISyttaS9SdE45UlNrRkZm
            ZGFNOUo1Z0VPczM2TFlLK1VLTHRkZ1NsdFVzCkR0TWF4U2E5N1ZaOWt5TjdVMjhW
            bUx0TzdpRzdTKzU0U0hvU0NoeGxEcXMKLS0tIHJrNmZQVyswZTEzT0c3RkRrQUJr
            KzVGaVI0dEljYWVGTDRVZU05L0IvS2sKb5IC8EMk3oyQaAqGzFkOzI8Z8maDN9wm
            eABM/sAL6bGNwtndmcVnn47m5VnBJrkRtCQK4OVhGcC76yA1ap0dZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T18:36:30Z"
    mac: ENC[AES256_GCM,data:dFaLoOcm37x7BajgHqid+lKmjw/TEYmsWBwTY8EAryp/DhrK49Ox89MUFuGVb2wyj+rJcq0JWDbPhXPGVK9WV9buv62cjEx9jviszeF6zxKDBolx9FchWATdbBwT5C/mHF1s0ppI3PWbINUCwyIl075Cxu5SxwBMUX3KWdE6x5s=,iv:FgNzmai9h9MwHuBTAwNbSsYJPa+Qo5C4WOslnRXT5ms=,tag:zfGtwlVFPVgzj8wUl+atzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
