apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sn0jrnsz6BHVfZSR/OT9NMNrdb3fp5lqWhFDfQsjiFRtYT1z,iv:8fbgGFSuRyLzLfe3iEh0GIAy7IDpO1W8T5zY+UeId20=,tag:7JTdk8VbyoWbnIkM/25WoQ==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:V1gXflp7c0WssTdFXE+jZVp8qlFcWNzgu7sQqmq3lwzEa+vOLbQxlmmLnUK3ESIYibUo47oqB7GKFozfQc3ExBFX1pLjiOq1Vc22+EwEj/oiC7GsDR6GY5BpW99Y2FG6GufoWOlln1RmWXvD+OJ3JCBxiDyPF3u3kLfZ5jzd2uD7RkpiDbHHImRZ6pXz24sRSip3OBKUHqlUe3Lc4uuN9vgV6vMVk7+bW3GZ39xdiw==,iv:wcJNzbN9O1U6uoebapk7r1tIEbEQhDlURqgemVCsZEM=,tag:cj8mqxK13a/nstGPEfqr/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb2xhZjFHSVFjK1Q2Zk9Q
            bHJabEQvNnZvb0RpcVRTU1JnblJOOHZHMlVVCng2WlVOSTZEOWhLeFRLNk92Qmor
            dTc5V2V5YkNYazBmY1VheEczV0MydXcKLS0tIEx1M2JPakJYVWl3c3p0ekl2UEZk
            VnpkM2kwb2xBTVNFRVhUaXNGUERFaEkKv7LBb1hb1sVJZyfQVMAnQzhFZ1udDRMp
            AGBU5bs+27CrTd4fkixkTN0aqPCaDmJh2sWkOtmvAGHg4TbIJd5Jog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T18:15:35Z"
    mac: ENC[AES256_GCM,data:JiXVJAQT6e2usaIp89KmYQcnj4XoZwPn1SnwYJzaTv+XGu4Pjoanks0Iz39vuaTe0rUn5BkJSId8fEwad3OlX/OuMpoAfXij2EcF+MBrRlJ0L64EABRUoHvJ5sY0LpvUihyc3bJJ0WGPohq+YGaxrwqffIpBn2EYBqH4ktcSOGY=,iv:T2WKs+bcqMEkpCLrVMk9GQpN1Z/fpX9eDnlVK9vjiYk=,tag:YdhOXSqQCBszuIz98lKaxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
