apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:P11p7Cw=,iv:W8Se6fvEqCFq5dxWpbG7brQxchYvwBFburOSALFNp/o=,tag:3zyn+VyPf5cOK2wKytG+Dw==,type:str]
    admin-password: ENC[AES256_GCM,data:dq4CJItOr/N84hsTYU/De++4nE1Qsj68,iv:A4fDsXVXLb6U9DMsUU7THNxMExoDYvma756Im8skPZ0=,tag:bgUpnNKReGt6qw4wOFLOlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REkyblU5dldva29qWlYr
            T24yTGNnaG1LK2RVYXJHQWdrcFoxWk1PTWdnCjk3aEJROUVkS0txQytabklyWHk0
            SkpnSTl4WWl6SnNOQUtYRS8yZjhoSWMKLS0tICt3NUp0bHBQMmY4YkxUb2Y3cTl1
            VGM1SjBmOXc0RUlaWTBOSmMzci93UHMKGWREmKoQpjxLkqUBqRr4xEfUJVpsCIpc
            L6fetXPO4pQuRpbgP0HH5JgDT3CRFp9Kef9STnspgvPFiDxN5WKnrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:22Z"
    mac: ENC[AES256_GCM,data:THa+ULr1KMisWOxyXg0y4tCqxq2hhvfqEUiSWFn9TF7+6+0AQ2BOVhOaMwiwYiX3//cP4/490eiGqOMeYkxGPqdIHGyl0ebBZxkJRhjOv3cQkUESJU7jtRTY9WXKrWzM70dCjVM6i+X9FpXebr1UXlpBEpcS3HpMtJZ7pmtxc4M=,iv:WOYhNPwHrHy0KLVuv9rJ9jxpR0dkEGf89MA8cnxSUdk=,tag:l79io6OpO1r1Uh2im84FRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
