apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B5tXcnbwUfZ1eZSP9QOerjyf+agNhRShhovpymfVVBgdVm2tQLlilg==,iv:Y196AB5FuceEQ1KxEQ/srG71q9KtFNQEt0XaJg5FsBg=,tag:DIrPdpkr5559yavsd+m4Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTnRpWkMwWVQxV25rVmc5
            VU42MzZaS2hCc1d1QlRZUmFsVnZFUlllL0RJCjkyei8zcXBDRFdxSGh2TEo2YVRQ
            VGg0ZXZrZG9QS2tFN0Robm54Sk8xancKLS0tIGxySjVST09uVllibk13cWdvMnZ1
            dFRBamR5QVVFSVNUVnA0NnA0R3YzYUkK+qY8g3Iazq4XHHWxnUUlyoY4J5MmFwN8
            DZpYOFII8/qgZHrLde1OzCjARlCTOTTK2i84/EjaUBxBR6f9YWHmYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:22Z"
    mac: ENC[AES256_GCM,data:uVCzG/zh73FdmQMG6E3eJwuQ7lUDtqoSfyrTXoSTG05ddonyKqO6qqKYVT0YLOWCRmMs1qsBLGZ5oo1inugW6ICcJHrjSU6X1bjZgdE0L4EIDjRYgPQanHVEy/zv6RqSl7wWJv7Xh24AkBQdU35tf/2USPRLoNjTponPghMgx8w=,iv:nK/Yo5QobQJ+5hfXRTWjn/XoeZ+Lm8qDLXJ8VsWX/xM=,tag:6zJ5VadU/iFPtjMaPhL/YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
