---
kubernetes:
  children:
    master:
      hosts:
        frankpro-1:
          ansible_host: 192.168.1.121
        l1-1:
          ansible_host: 192.168.1.206
        l2-1:
          ansible_host: 192.168.1.150
    worker:
      hosts:
        frankpro-2:
          ansible_host: 192.168.1.207
        l2-2:
          ansible_host: 192.168.1.168
        nuc1:
          ansible_host: 192.168.1.79
        nuc2:
          ansible_host: 192.168.1.148
        nuc3:
          ansible_host: 192.168.1.194
        nuc4:
          ansible_host: 192.168.1.188
