apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:U9L3epA=,iv:5pOveN28Un7ys/WjvSTbyOFdJeYVaBzePI3XYVo+bJA=,tag:9u6PnRkVLAObSxb/JQ0Wjg==,type:str]
    admin-password: ENC[AES256_GCM,data:nS+3X+1/c3Y=,iv:cDG/jOPjF8fsPtaGwSIUlCnmgwKnTRF00jrI92V5DDs=,tag:6ALat1zJGSNJjpxWxpPyIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTkxrRnZXdmwzV0pRUytO
            NlVrVVp2UGIxZFhEZllqWlRMb284aVR6Y3lBCjFDUzI4MjZyUEk2LzlSaTRiOG1T
            Yi9tZk8yWlU5aDhaM1RHVGg5c0lWcVkKLS0tIHUxRmtRV2dLcG9SM3JabStndFgx
            Mk9iQndpZ1FnVGlkWVFEYzRqbmhQNWsKnwN4yyuCGVJ0J3T8QU10qfKsQA5ReJl2
            U43iLQo2bTNwNZX3wdkRs5UMfL/Zm8EgcKY9vb+XGKCrCv/M0xAsqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T20:35:20Z"
    mac: ENC[AES256_GCM,data:r6y7Cv8h+BDW9fswbdFq5TxZX+H6dV9YouYYOgt399vsqMSefmAH1CUCe+joE2U0N923hRZpYiquvFUlzZsKcmLJq0Xh93y0t0mrN2ZLDSW5Cpm90wS+vFJb+VkSWRVytFz5yEWnM2JPGXei7fnbio8KgRet5KDgGg4gYE296HA=,iv:UYWEO6UUsWSNJL3HBNzW6KIt9YKgJgZoY3utRfq5ML0=,tag:DfcgjI7P5xt+VDHE9JfbBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
