# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: media
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:f1uM62VfwPk+1IvI0v+Al0BxRyYy82ZB8/F/Wjirj5k=,iv:rsclNsSlXVhqFKbzNtNYgqX/EOeuZ4HaFcfesDM4V5M=,tag:0LCb4bjicNWvHvCPBkyyVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGRlcVZnSTZvQmJ3b1dp
            bVRDeldkSHIzMm1aZDcwWm9pWitnT0tmdTBNCmZwM2xJYnN0dzFOMkxmMlRGdmUw
            emlGZklkM3dVUGcvMjhiL2l4WXo3MkEKLS0tIG9NbzYyaElYVTM3a0tsbitacnNl
            SjhWdlNLb3hJWENsb0J2TXBFNm1KSG8KGAooVMqcZXuhaHpYfMk8aYxPzMPQQkrL
            PFwPm1pBeSfmtJlluzRJeQXh5o0Ng2U+lAX+5RJdtDawLAql9Ndl2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T22:55:20Z"
    mac: ENC[AES256_GCM,data:OdZ/V9O3AVZy7fIceQTDRBFFtXof64DR9GGrLT8BGExe9Q2qsaYzZswdYUKgfDrDGs0NnwygxrX7bd7KRX3OxWlvu0lygMLphOA6QeIGNC+y9VPVy9KwD1wEMOL6vtooDy8rpyU7FLG3af+JPval3K96pFZLj8EPG8Kpmpo7rqU=,iv:UVtWQcJiwQ3jcww0rz+6Xp+dETwKaZxyGt4kxgaRFRg=,tag:kjl+lkzgDjW2PvFoftWhIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
