apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:C0sUbHupPjcmpvFdDJng/0wKK7M6tAqRI6Qd3N8R/9u8eAq7AQ==,iv:GNyH4t0U8Puvedl9talnZYv2dElpK6aJSf7wP/3qJvk=,tag:baEd9yHYKaetmJXLnLv3BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VzV5elVHQUJOR1c3ZFhi
            dWxSaEpQdVp4eFFQRXpabEx6L2t5U2ZMVWxNCnVOSkRQVTNnZTg5SmxSN3Y1Wlc0
            Y3F6ZmdBdkNza2RiTXowRGRzcU1pNkkKLS0tIDUrSkI1V0tBRm5NTGRPVWFlaWEx
            Y3U0dElIbHdhbjE1eEdUTW12U1dRaVkK+57Vgua9mH/KfeRUKqBWdsdMZB1gZCDj
            OOBRw6ErEL2gUhYzgvl3TSjc1O09WJWHYdGIPVCy3IPftS0MzcybRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:21Z"
    mac: ENC[AES256_GCM,data:vUCTTj92jtWwGNLO1XJkgef5Pn3pnc1VS18zWIZHM5MPEahGDea8+0AglU0ixmTP18cUD1ZHJTLAr+w8qxvalQLI4L63uAhJ8NtfGIMM42hx5eT9MNcch5q1MsabKESAnlL7921cS6r9pmh7sQixvyzSjvoMZAf4cTpntU8rdIo=,iv:pv/1uCnPSUat7AXUgpBLqhSwfojwlwjd5E0HE4E6sBs=,tag:q46HOKK3a1fPj1NNBgyfew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
