apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BfrIjAkr2PQIoPhXcttm3LjH3mQAMnoOx9wno5bAM312UTQmUupL1Q==,iv:ql6L2oPM1YlOMuyhzSZDZgiTpZFqypRd4ETNa9+P5eI=,tag:vvNXmYQHydnUugnPsDoOPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTWNFK09XSzg4Zjl0NFpX
            eUNTd2ZhM0VnWW42U0FGbDU4K3AwZnhoaDNzCnBhYjZBNlUvdWViWUk3ZjdNa3c3
            aUQyMjlqTENoek1xNmFWVG5YcTFJOFEKLS0tIEJFU0hKcjZXMWdEQlpjb3FZcGMv
            dHFmTFBaUG9JUUdhWDRnMXNNaEdXT3cKuYgHo6O54fNmjqZGlgaFz5qt+hOXYl8y
            V5lnBycanusncchKifQSI6f5rK0pLaKrIQwi4juvNwmeH66vrcp7pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T18:36:30Z"
    mac: ENC[AES256_GCM,data:KL/wLZxWuQd/PXFcDzCvbj+YvHw03DqoyiONyIrvYfhP5c0xCB7umk0NSoc5dOuSpUbyX4AF+wbI5SxVM5HoGqslF3xl9lqEq1tiQYidRORoZn6ewi7ERLZbGLMk946gnkEw9oPhALzXSYUtda8yABIH9A9KIU1foCr2vKl7ids=,iv:u95fZqRpUgTF896gyOfnnZ6u/7gJ/YyUs7pn7k2lXuo=,tag:dZGU3cMCWF0nhBmRb4NESw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
