apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9ochHKcTWhq79+hZlWKpgFiFjnui+NG5aWJ/oAMd3vz7j17cPNbwUA==,iv:N8GfLjvljp3xob+T7PJjgkDiqEctZsdk/uzJAcmV8FQ=,tag:84RMac1DLAcXX2+FOGbWLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTHRlRGtmeTVlWnk2dmk0
            QnlzU3VzNUF6MU1DdnR4VFNLanJIZEJJNlZnCkVrK3hSZWphSVFka05qamt1Z0ZD
            NGc4MTlzeWpIRzFxR0J0RkorTTAzRFkKLS0tIE9YSEJpNndYUVRKaWVBeEM4Y0lu
            b05PZy9TRnFuZzVTSWsvejdZeDE0S0EKDNCTFo7zcgikZPsnTINhlJG2hPiDZNKx
            bDpPh3AwTf/MsgbLtPe1GV62Qtuz1RR1E7992flxD79pH7iXnG1k8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T18:15:35Z"
    mac: ENC[AES256_GCM,data:GnMMepxnfYQ8guutIpyjoZzMFa/FfEI2+q53jR6BKZRm7bkaxJz8i8sTksWarGD9vJ7thg2/kFwKkKEkrr2P3y+wm+GZi8lmGsU/yokiudN6CTUnREUXAom2QEAWu0qDGq8l9TXAHVaCdcdbtcaikaBgLWpTkqZiV/5isSCTmmY=,iv:tH57hck3dABoQgYHZsaoYALw44Hw4eoM3j7zZG7Xnq4=,tag:QxrYcRMje//Io4Bh/Mmkaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
