apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:vIuxeZjHLr16gpA0eGv5iOT+Lr5t+0A=,iv:88a94UH+VkGW1eS90w3YxKA8XLOLZOA2IbUYvRwrAWE=,tag:Z2dMBtppp06ABizLNdIXAQ==,type:str]
    api-key: ENC[AES256_GCM,data:6DxtxURgzKikJAV5GCIAft3E1t/fcyUlbgeGjgecXpL+eIeNnA==,iv:wbqo31g8U4ROHRkbsN2qoZcQH6ZEgZEaeQ1+HP4lI2o=,tag:VLIpoTwX1318KWoJnz7Kjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdmJJeFhXNkZYRGVxRHdM
            SlJFbFA5QU5uaXlJWEFYSHdDR1BNWjVCWmlrClE0dzZtNGJ3QjJPcnUzejkwTENX
            akdLQWlMUG90YnNnaElWbGoxRjhVNE0KLS0tIFpIMkN6cEl1UUl1alo0bGhsWlpS
            aW9JYlUrVmxmYllSNmFEUjZ1a1FOamsKm0u1Rvv9scKR6oLrlsQ1zFlfz/bxWhAg
            eT5x6uXebhB1tHSLazwwfMgcrPUJ7di430oLONhZwiBDNSpTvGUOHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:21Z"
    mac: ENC[AES256_GCM,data:Lo74jWW03+TUK/nT7XCZRqoVIek7rHAoSXrVs8D8SkN9QMU4/gtjzX0XPgyeSXEB0z2PWSQRa1f8CeDqCG2Y3OZH1MFwTF2eLc4zRuJO79/j1YDqtP64xmuoSzVf+PdSgYGC2pFo2sH4+toydUwIs6f+Z90kFabl0P2w/iNQbYw=,iv:6C2P4ABbohX45OJLAJ1Hd2/Iuzd7UI6ay706qKPl9fY=,tag:f4xqPc066GDb5vVjj4g0zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
