---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      version: 1.5.1
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/onedr0p/readarr-nightly
      tag: rolling@sha256:7ba65537665eec4f2239eb1ddeb50240e98afcab44e2295631c9e30bc5a627f1
    env:
      TZ: "${TIMEZONE}"
      READARR__INSTANCE_NAME: Readarr
      READARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 8787
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: "book-open"
        hosts:
          - host: &host-release "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: &host-custom "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host-release
              - *host-custom
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: 'OnRootMismatch'
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config-v1
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /data/media
        readOnly: false
    resources:
      requests:
        cpu: 10m
        memory: 1200Mi
      limits:
        memory: 2000Mi
