---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.3.6.8612
            env:
              TZ: ${TIMEZONE}
              COMPlus_EnableDiagnostics: "0"
              PUSHOVER_DEBUG: "false"
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 80
              RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
              RADARR__THEME: dark
            resources:
              requests:
                cpu: 247m
              limits:
                memory: 1Gi
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness: &probes
                enabled: true
                custom: true
              startup:
                enabled: false
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            # runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          reloader.stakater.com/auto: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/name: Radarr
          gethomepage.dev/group: Media
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        globalMounts:
          - path: /data/media
            readOnly: false
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
