# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:Ga4qctM5J6S/GI3Wpsn1aF0/LIOeFgeiWHYTmC7LYh8=,iv:XL7NV+lzUIMzeHirXhOAFyYpdO+/HIP+XOanaOfPOnk=,tag:y7mszt+YFB+JBkQyQozsdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ2ZnS2E1UGJxR04wbzhu
            ZVZNL0NHaFhxdEFtR3NGSEZPY3UzTWFrajFjCkFQNmQ5RkUzeTFnelNPWFAzUUtV
            dzMxRkJzOG5RNjFJeStWOTAzUG5rVDAKLS0tIHZpMWo2ZkFHWEx5cmxaOUpzdkNN
            ZzY5SG5iSFRDQkdGOXhrcXFkNkxPZkEKWGsjXbQ5+QSAQUZvcceCnXkMPn0CJeFO
            VpfYp6YESrnxeCJ5JNRIoJKGD6MXiais0IKbB0l3T8hsx9nYrijquw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T22:56:07Z"
    mac: ENC[AES256_GCM,data:R/CGWjx1sQJZ/v5d9VAeaB/2v+es5GRddltanMyXRHlTYKbm+fnvnvS5i9Sn5pvNCiqx+9LV41Guu7QRYBbJ7NngrFCBGYfdcVgm0mxKoGIEENpSOxjgEoxbbwX04b+EwkgT32rzODJtOMlMeOMfjKEEcaQAdad0TvViP1Bnd2E=,iv:l7pw/e6qSPrRw6A6uvFHdBantHMf+QRZ9yq149BBspA=,tag:DTcKM1AEy/dcpdSrh5PjEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
