apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:s6s+pG0=,iv:ytNDEcxU93+proNvftxeBMtSKAeWOfSHqwfpkkURVqA=,tag:GOIVX/eSXZ94Bu+zW3z5Xg==,type:str]
    password: ENC[AES256_GCM,data:s+9e2Q/oUd2M4T+M2qiDlVUqpfMAbobxc2lKM3KyMSqXFw4Xj5NwHp8LjjHRMh3NZ1Nyap49Rk2qh8j4,iv:GUULKBBoNuxTXEyhKKz11vXjqsg5HvwaWnrP29nvIKk=,tag:Xk2sSJeC5M7quSwRXMG30A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobys2LzVSTTBUSzRCQUZH
            RitKbExtejRVdFJ1eUZmaDJMcnV0MnlpN2drCmdKRjE1NTA4NkpjblVsUXZtZ1J1
            V0MzZ3FJMDNWbTN2NkZFcjhoWjRCSWsKLS0tIENCV08zdDJXOXk0MGh6RWNUVy95
            b2JlRkV2c3ZuYTFGa1pFd2VsSGN6SkEKmW/ebSWlqZqVMonAij5ai7lo+UOl5uEP
            Q7pcJxuYhDOIoaqSR7cnG8qpGV4Lk5eDfVk4yspJamH05DZ2vlBTrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T20:25:31Z"
    mac: ENC[AES256_GCM,data:axi0ytyK2MgQiAhpsu6trkN3vQ0GuhZG2+sk/8iaqSQyY7XJVXxrYzyldbUfcEJO/p4RVX4pGlV/gWohzpg/29ZW/JMtuhgJM1rt6hddK0A2oLUt75J+x4Da6IrTdJC5eCkFGJDYiB0533zzrZW+kSku1HU3m8c1oTbjMPHPRM8=,iv:dy1izPG9SB8e2n8a3TVa7+jQxTBLq0V6ffJq6blVweA=,tag:gTIAwOC5AB2ON2Fqr1p+qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
