apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:covBfy0=,iv:7lEUKw/arAiW8QcfFYXa1RUHVZFY+jeAeoYl021CZFQ=,tag:IBMMpGejF9Ku5f99Z5BA7w==,type:str]
    password: ENC[AES256_GCM,data:Dl8BqRU2EJOUn8ZoOxSQ5vPTb4b+xqHcc/kEmuDg8uN77ck8QKn2WxQ7r8wyDojdaAFoMznNUSVrqEKJ,iv:UzJsVetqqSCb46C0HFruvElEibyjpou7rQlNSaWet9g=,tag:Ri1beBn/Jbb3Ybcj2TCEgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybTNlcUxYdU1CZ2oxa2FM
            ZUNuWlMvNmZvN2FOcU5ZeEM1MHRwQys3U0ZjCjU0TFBWSWxaMUx0N083ckNVN3B1
            YXpOVTMvbkQrTkNSRFhHWlI1R01icjAKLS0tIDBlRVJTRVB2Nnc4VjBIVm5pOE1u
            eVAzUVhIYjB6NkVtUTlWUENrVkhmbzAKfdgSSaB4aBqFaWRHHUdHdr6Nj2Pjk6gs
            P/FoifAbSrcV7auhUJiz34qahuW3EZ92KDA62QCqNo6ZNcT77/+xdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:22Z"
    mac: ENC[AES256_GCM,data:3hjMg4hOPIvyECh9T/eHDr/pHf1rvJItia1YgeBDBSZ9Poe4xH0BYP9deDsUGh3OOgVH9ZpyEk3ABR51jbpQmme7py9tbML0G7eSpfMsJLB/+CxXoFE/JgiWbjsiwfua0JjU6hY+hZ1AUE9COLvvKWMSY8hoobCcF01lsCN0D5o=,iv:Zv6th5COqYiZb9mV088UDSzKE5OtGu7Ri6rjTECUAkY=,tag:MY9d0dxAo7VsBW6vhC15fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
