apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:11GuFAB4jktf2XbsNDBYMN52HGQus1T85wLpSscJFLuE1TKO9HBA7ebQqoE00B6q3HrAPY9t9KORmW2fwDj8O4VhNzoDrH4N3YjtR0MIqwSBa4NgRabGUd0gL71rPQ==,iv:vIkdXAvjedI62lfmmTVF1I5g4E/niwUBZneW8z5TOQg=,tag:FHl0RRQYXTfayN55rcsxYw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CVNmwV3ymXauCtXV,iv:4gE7Jqhkzi6fEbfFYCwDSdOgXsKSf11JNr/blHhiv24=,tag:xDDgt24uiK/H3Qe/l2tj+w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:g7ZC3jiYvhQUd3ic4yFAWnYoCH5EX2s=,iv:ozvmMICtGamtkBZYA+u12r1Y2licwG7/rEOHw7zfkOU=,tag:5pbqKrbjVmi3iC+WX4CzpQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xYH8auie2RV1AHLEJ7a00efLZfJESnoj+UFLeqnUjogr8ydW,iv:U9aNerEUwXMGB0Rcfb0FH4ZLr228+XBgoqL4eMUYMC8=,tag:9Yr/cCLfUWYaFfnnIT+FsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWUV0SnR0YkY0TmRySHlG
            R0t6bDJ6ZE9KUW81ZVpEMEJNNnNLOWJRSHhzCkhta21MZmdOdWdSUEVoT0JtaEpa
            b2RwcmpsbC9vK2cvNkhnbE1jZHZEOTgKLS0tIExzQ2JWQWlFM1llQmpzSlF1VzFt
            RWFvRGxZZ0hkeGlRdDRZVlc0TWZ5TWcKYMOUUP1Aj88IMlKj+OF956wAndXgvxbc
            IHMxfP55YKQJ6Z21PTh2vbtN/PEmssWsWwNTOnq/rd5bn3BLX3V9yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T18:36:30Z"
    mac: ENC[AES256_GCM,data:O52F/Jt4T5OSSWfkQFPy9/vBp8GCzB1B7+ECK0GEEcTe366Z4Pbap2xKqiKa367Xq3bTB/FRrpmWcxLxmVi2+a9Nlj0EaF6hIWGYJSbcbIoia58mUE1PThqRIe5S9XIwZ/ylpGPV6x4k++ZBsonKwwu1I/znrzDSeRsMvGBQrRE=,iv:WYldySG/pZRf2wlqbRdauwM3yg52XokI5BRm4QiCsJI=,tag:ZyCSNXabBv8VzUrIqY87Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
