apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:aXe/Wxc1dJ5Bd6UkW3EXQqRi7HWNS9ZGCY4koOluuWsbyj96S6T4/diWBN5oGd36uHnay3C94GDRgzb6c/MmglrCW1mKqPQeG9jYY5PJWpM+zGqTiFtXKK3uwxkOIg==,iv:BJzyxc/6cqx1o5BisF9Evs6Sczl5k7FnZBQ4ccGCQ6A=,tag:H3B9hD4pIt2Z4UOybPZkZg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dHrTGTjfc+PwpREJ,iv:jE0K0Vs691/Br0/lTcQMMpfQAnoiWQlEvYuh7imRXrs=,tag:oAWHfgUvXbUOxYNnfaislg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jDkIP5BeKOG3zuhJOQbfeVdIxX8JuMo=,iv:RHFbHOKD+fUUMZ1yRc4X1WDf/+jr+hqoPQ6dX0YNwj8=,tag:asO+7yAG+qlB3AMTK2/36g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:x+gsyDgtzUyv3CicUD5xo9ocne9N3O9EpU5jnHAc+xYs1Dkz,iv:u5UGrwwpFxcTaAkrliPlnhFfzPvI/X52U0lupvaO1eg=,tag:y1yibctJaWW6fB8zW9v5Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWGsvdUFGeGhzWUwzTUkz
            VzJ4aThDa3B4SldQMGVKTE91ZUJDY1BEc0VRCk00UlUyT0FtczBDVlFlcUorQy9v
            emErTXNBZ0V5WTJzZ200QnV0clAvQVEKLS0tIEZseUpEUHVYb3laOFdVWHhaNVpH
            T0xYdCtreE56RXZCVFhxdkhKUS9xdkEKU8bghqnE1gVwdfkF9pPGETINvoW3lvxv
            qLkXsLV5CNU3YQRlZNftWu9rpeT7atwGa2AcXb4MbLd9r4pvB6b0Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T18:15:35Z"
    mac: ENC[AES256_GCM,data:ZI0hy8an1V2PEBxgR/gnFG1i4Ay5b2pmnCv8QyrgH6rzEfIEj7N0EO3sF0+YCAMGwVyGO4aTB+m/h0TAy6NFXjLX1U+/ywQSVKc3JISCEb4hcWfhvMQd5HF4iH76dkfaf2dKCu+6qlrbMu4V0ysZYqQNXaW0FdA6LvjauQzYS8Y=,iv:hwcvXWOaY2R3fo3cU80P9mvceuEHqoOnkeIIgWmh6bc=,tag:tt0LxKKfO8zbv0krwDTDWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
