---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/plex
      tag: rolling@sha256:37d2f31b16caf3faa4e0e6a6a9f0cc838d5f4dc878ef3b2c326e726026e73ec4
    env:
      TZ: ${TIMEZONE}
      ADVERTISE_IP: "http://${SVC_PLEX_ADDR}:32400/"
      ALLOWED_NETWORKS: "192.168.1.230/29"
      HOSTNAME: "plex"
      PLEX_CLAIM: "claim-fG95n8Wjt6syYxPwoD_C"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/icon: mdi:plex
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          # - host: &host-custom "plex.${SECRET_DOMAIN}"
          #   paths:
          #     - path: /
          #       pathType: Prefix
        tls:
          - hosts:
              - *host
              # - *host-custom
            secretName: *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [44, 109, 10000]
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /data/media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    #   intel.feature.node.kubernetes.io/gpu: "true"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: app.kubernetes.io/name
    #               operator: In
    #               values: ["frankpro-1"]
    #         topologyKey: kubernetes.io/hostname
    # resources:
    #   requests:
    #     gpu.intel.com/i915: 1
    #     cpu: 100m
    #     memory: 2000Mi
    #   limits:
    #     gpu.intel.com/i915: 1
    #     memory: 10000Mi
