apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:BzYtxn8Gik04IasNe8RAc1ow4Cr+ee+tDsbnDAnMuBzUs8c9,iv:4XDPRymhB8QUtatDcrbOqNM+NalV2npz3jIwwh6qLug=,tag:d4ZWr+yaLNuHHREjWthbIA==,type:str]
    credentials.json: ENC[AES256_GCM,data:LBO7tZFlFpFwIwen5mZ7P1jFLDPhV/5bx7lr1d932RosIOfLtzp3j/mHuckNmzWs2Ci8XiDghMr2rxekouPP4hNAEQSQbbxXqZRpWBTJxbLeO/s1u+HtTkW46ykTLqf7EAji1Dwg1dEw45fvntCC/5te23YbjO4ecvm5w7raPykoP9Y6VJmPVi/TcPmQfyNslG/AN0av2Gor+8rl4vmFC+jIMbcBXx8SeGedyPtFLQ==,iv:VGvGqB8aGExnlsxmuVtKhWXqK7QdszQh1cDPJIsQzLg=,tag:3S7lDT8A6/HIfqJn77K3KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVjh6Q0ZCVnR0bDJpWjN2
            c05lRWxPM2JOakkxNmpYbmt5MzBCLzFVYnlvCldXYVdvSzlZU3k3N3V0RVRHMC9E
            MTFwdkJFSjIrVzNmV3czeVZyRzZ6ZjgKLS0tIE1TL0VYd0E3M3ZqdUZUMDMyUUVn
            TDhCcXpQUjYwaG54dUkzTEY2cFVxUDAKfiY3hvueG/ufPFeLhO92mnEY9mZsSZJ0
            zAF0sTTUxQ3tOWHcpbZD/r9PRjkacfLIlP88MSsdzujwCan6aS19oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T23:13:21Z"
    mac: ENC[AES256_GCM,data:/85DsewvHFDkWQq/RKLouJXmMfvOASqMJ2euCilOR2zI1EoftN4NYf43/Lh/MUOMfnhBYfVa6OUlNeAf58JSS/G6LND8oNMhCE452/6jkKQ69koaMfBNtU/EZOC+J9qDMlrU1qDDApuK/j8zGIi5oaNCt7g/ANdeDqg8/cuwxtM=,iv:svnBDaka8Y/A7zr43tkCEhzcjfk97DZUndO8sP2hyug=,tag:aEjnYYL6+Ke+BWF+gt0ehA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
