apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:X7Y+clgml+ZtK/lJ+xp9reImmBpw4+Bf1despYu8y3k=,iv:aAIE1L6Of6qbQFL8SO4ruu1S1ZoOwzul9ymem/JhIWY=,tag:6rvAy7xlhPyWk6/LqzY27A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RWZrK2ZEZjZuK25nYTRo
            TW5raGtkSnlMaWJwQ3BSa2YxM2lQYWZTK1NZCmNRN3pPeGdsUGx0dEE5OTBTcnVs
            TWhiNGlLV011TG9nc1NFNk9ISnJ3d1UKLS0tIDd5bnlzRXhvdThYd3o4bEcxRkpI
            eCtkZXIwV1U4aVNTMmdLV3RRTWlhMjAKy+6AsXMwiAE1ZEH1fI7cyNhQZbx9J+ch
            XvOHG+e98qOsn/WvBowj/evJXbOgtRM/FW9x1MFoBxV85kGX8ztSeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T18:15:35Z"
    mac: ENC[AES256_GCM,data:L+ilUlyiXKnQOsaDFwKPWJJT5wtnShL/ydzAqjELuZjDVyWYxeSky2uhY3Q7EfhrYL/gEvL6UwJb6lrxm0/4HY88GLPynoTquoffBOvhj66f6cqHr6Xp8nnCu+hYaqw75qrMY0uUqJV0Zl+G1iH8Bn32H0Ho8biscAUWWeoLfQM=,iv:yfKYhBNCLXIHfoZJyOXjnO2Dha4GkrOCa8xcbAtOaHE=,tag:gb3bCHlo4gIHctaroPo6sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
