apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:t63eD9LVfXM6VfOfrdklzv1gxDOVG423bUhysqCE1Xo=,iv:hFwCwzIKMeW342hQcVghGB6iXrDrFwxLD26xCG/1SDs=,tag:Ez266aN0H7gvnyeK82aYZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVlRSUG1BVEdRdm1XcXhs
            VzJkZlJkblVJcmlFdHVoaXdnV1VpWENWVkZnCmZ5VTNPclVUMzRZS2FCY2Z4SmJT
            dExtSnAxdlAwbVFicW1jMk4zWU5KUmMKLS0tIFFtUUpUZGV3dTN3N2dMTkZsK2Ju
            MUFXWUJsd2FuYjZIeFFhZ0NaT2c5RjAK+4vQRwqqOZzckoOlb3Kdd7+MoBk74sgB
            ppEDxy3KlnctboxdTOH9z/QApSrF7dtuRizo4ouuIfZ46NOif/z4tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T18:36:30Z"
    mac: ENC[AES256_GCM,data:zXorXsSlIvjZ05ePT4qcqv1W12bMhdXm0Td7QNJ8MY1X+zNck16bke8AoY6wXPCOqk01QHs3VGBYiGW+gcniq08oK7g2EnrPS6VKutQ0YJ+sgZ0aqiLaGFfowXxox3xcDBEplXsCVOzrz2LYWI2c5b16gJX7F8RvLWEXI5zHMRM=,iv:uIhDnqnAKVzBClQzWpV3JrvG2ubaPlRcoNtProsSvcc=,tag:7v3YsdRuxBeOJOwcDPCEJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
