apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:gQRkWbkYPhJxTpizF55uFLePv1aDepW7Hw19PxKzFes=,iv:vmrgo1H5jnbU3tpVjmUQ6ClD5rfyaucSAqaehngDPP8=,tag:y2Oy30Tx8LOWnDDkTHM+Rw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:we4eXR6ISuai/TaIW7wdDIBTb0/lEblM0TM00AKkL48wROPT,iv:ry75X+rdgh/KTPfqBiS2Bn9aSS+nWVaNcX7NN4Yrt4c=,tag:Q+kMNXXWYgGblsTBu1ZWIQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:kR1vkkMFvpx5etwkkVk+Gg8DcuA87Cp6lZJe1lFOK1s7XXhtq2IqEw==,iv:kygqQiVN1ekPLSXIYKi9eOgQvhVwKM2wn71L33nuL5k=,tag:oUdMy9Gv6ngPGnCdtk6MMA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:ZUtIsKc=,iv:6ybVqq1/atUd2wlM2zGCfW2tX4KnJDaEBHfPPd3RvrA=,tag:8caGMYuhM0c9sFf1MkRUHA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Vd8BjWiEDAM=,iv:EDqEL1tE+pdXYVpJm6+cxs6MKc2SVrmRR+ZsL+cRUw8=,tag:mVJMrBfvy6n8p2Sv88fLww==,type:str]
    HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD: ENC[AES256_GCM,data:M+Yh9kWGqGo=,iv:qAErgFsaebWGSKZ7HCrYL0L/Nx3vhooFSHpEEymxYhU=,tag:VS9EmwrLtrqP63KoOHbcNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbS95WUV1dGQvUU1Rc3VI
            bjllZytrNjZRVi9XanE3VTA3UkF5OW11TlJjCjRSU2pic1BuOWx3bzkyZmZYNmNq
            S050QXZhZi95ZmJIdmJDNHVNbERXSWcKLS0tIGhKZ25FUnlxbHNteTFqaE1MbGZx
            ZzRnOFBRWFRRYmVGbVpEbUpwYzZ0N0kK/b6NRydw8H+aIpvBAsVrk+btQ72KDrhC
            NsUv57baX7726t5HJlQ3p9qlEcJ6Kqw7uN1+gKll8dRshwwMunp6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T23:27:07Z"
    mac: ENC[AES256_GCM,data:2YFaVTsEH06P/K8p/Wu/LmOOvgHmUuNekBdU9Dui2kdg9R28yvTEoeu2G+tCF69WR89n1/Ha2RSGsZmTXld55jYoafB52jyup8xUasLQShv18Xk4XBGIamX3Kn00KQAIKmtkjaUEeZziDponlSN7+seX2DwBlTTCP+I8xV3N+b0=,iv:mAHsHqt9MmoOR0/dTqSWJ/89qDsHMmgXnC0zYJx80gw=,tag:U5TLDyakKtMriRxDDaZ3/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
