apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:gQRkWbkYPhJxTpizF55uFLePv1aDepW7Hw19PxKzFes=,iv:vmrgo1H5jnbU3tpVjmUQ6ClD5rfyaucSAqaehngDPP8=,tag:y2Oy30Tx8LOWnDDkTHM+Rw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:we4eXR6ISuai/TaIW7wdDIBTb0/lEblM0TM00AKkL48wROPT,iv:ry75X+rdgh/KTPfqBiS2Bn9aSS+nWVaNcX7NN4Yrt4c=,tag:Q+kMNXXWYgGblsTBu1ZWIQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:kR1vkkMFvpx5etwkkVk+Gg8DcuA87Cp6lZJe1lFOK1s7XXhtq2IqEw==,iv:kygqQiVN1ekPLSXIYKi9eOgQvhVwKM2wn71L33nuL5k=,tag:oUdMy9Gv6ngPGnCdtk6MMA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:ZUtIsKc=,iv:6ybVqq1/atUd2wlM2zGCfW2tX4KnJDaEBHfPPd3RvrA=,tag:8caGMYuhM0c9sFf1MkRUHA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Vd8BjWiEDAM=,iv:EDqEL1tE+pdXYVpJm6+cxs6MKc2SVrmRR+ZsL+cRUw8=,tag:mVJMrBfvy6n8p2Sv88fLww==,type:str]
    HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD: ENC[AES256_GCM,data:M+Yh9kWGqGo=,iv:qAErgFsaebWGSKZ7HCrYL0L/Nx3vhooFSHpEEymxYhU=,tag:VS9EmwrLtrqP63KoOHbcNg==,type:str]
    HOMEPAGE_VAR_DOMAIN: ENC[AES256_GCM,data:wiwl/x8QMkdqs6Hv,iv:yn+CvKFWkM3svG3NZTFZ12ay5axOqEtn1xpvW3GL4AM=,tag:iUI/a1r8rNw19QnVyVAe4w==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:jc8rCvzWDxur5YyTdbkZDFp2SKYis6FEOX0iCGmEZpc=,iv:WSwaWPptdoQoU4G3cjdjFyih/uLS0H4/NiRvhpqYUzo=,tag:6OmCtkTo0kP6Iq6lOhzxIw==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:Ih80C6V97e+ykbtdKrnW+5onokp3WpM8xHmr9tJwlQc=,iv:JMhStn1hb9uNLL+xfLP9bsaqE9blevV7RyKopnXa/BQ=,tag:VK87NwwElznWEB376jkrrA==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:bJzYwMojXD2Sg/FyJ/trEOeR/35pzBG8ty7ycDLiNRc=,iv:EckU8vf1cJ0apD1DoIc+pZnqBBx7XbZrWStNsFL2rgw=,tag:KJsFHRPJd9hfFzk/zAYtGw==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:4ndN7gVVGqhaFcP7CbRuvYG24nzVAk7AAqPffYjJLt4=,iv:QJ7Vl0Jq88new59pXiEmRqWJjvaKvaYVDHNsw+gJu94=,tag:oDqBbtAkDaETY74Dq85lcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbS95WUV1dGQvUU1Rc3VI
            bjllZytrNjZRVi9XanE3VTA3UkF5OW11TlJjCjRSU2pic1BuOWx3bzkyZmZYNmNq
            S050QXZhZi95ZmJIdmJDNHVNbERXSWcKLS0tIGhKZ25FUnlxbHNteTFqaE1MbGZx
            ZzRnOFBRWFRRYmVGbVpEbUpwYzZ0N0kK/b6NRydw8H+aIpvBAsVrk+btQ72KDrhC
            NsUv57baX7726t5HJlQ3p9qlEcJ6Kqw7uN1+gKll8dRshwwMunp6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T02:28:42Z"
    mac: ENC[AES256_GCM,data:jBuiilQr2s7xKf69xOAb3MZxpgZ1XF7VtFM4/443Av7K4VIz/aPc71Zon9XXweZqEoo1oXdayqOK7wTM31+/vip/nCxJMCftoYs1K45wWjKwo+ORsV4+hyK4IvtD0RWhl37hXLn2xK8cs6o/mpFNYIrWDJoARbA1xtcp84qA+is=,iv:jeYIe3hJXlmgXodcTWmnCqEh8XiVeLJAIj/oJ1P743g=,tag:zlEq2k9WagxfETijR/HvJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
