# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lidarr
    namespace: media
stringData:
    LIDARR__API_KEY: ENC[AES256_GCM,data:ImF/t0Iatnl8FejLA9s0icfTjWI1gprkBsmykGNIsKc=,iv:njN7dc2vUby3lLy9HonABuiylu3cY+ytAcooi/RJKAk=,tag:n65vBLvBVay4x22VX1DLAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd8jhlpl6va3whlz4myquexvprgfj0ts2qp5v7ghw6ll3xrn44tqy5rnd7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhejRsQkR4cWtmZi9tU2JM
            TnIwdzJjT2MwTm84Z3pmaGo4Q2RneE12UTJVClpQZ1R6TjRXUDB0VGZocDg2d2Rr
            bEJBZkkwQk4rTkZxRFp3S2xHdjZxS3cKLS0tIGNMWFdMMVRTbmI2blBiZTRCOVlC
            OEh0UnRsZmp3cnk3YWVpcXg5M2I1eVEKAwmXJzWrhBf64FwuJ6HefuUyk8xSnyQU
            QObt+7trAD1F9RbuOU+ICakyNdQwgajrPyP5qPDLq/cxGvnyzFwdnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T00:28:27Z"
    mac: ENC[AES256_GCM,data:WnCKpqusBeKmW18JTATQL8eBOs3f5cDx6QYWbdyZiZ4daOt9aRTkYa9TZNAHY8v1dXt4HZ9kfa3Z0VJD70hM5T9XafyjKY9PLiPfeKEde4iFNfgxNhGe2GFdULPXbbFnOdOIAmGdiJIVWIdljGw2MqzDEPseZ+rzbrp5FwlJQOo=,iv:n4WgdINo2WZSMAVU8u8J/9qMmvP0I58gOxrum237aPs=,tag:yLeRLVmFVdZCvwN+xLI2cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
