apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:k3/d6zn4munT/SeAYXqGciu/iPnLD51zOQd2IxGD3CIaQKaP8kwqTw==,iv:Yi8M/lN8jiXwPQEPylY4pMiVzfDQqwA+8SRvCgo1vUk=,tag:BB+dY50MUEGGmc4guox9mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OGdSNWl1ZmZHcHZKY0o3
            MHovWm1POXF2SlZRYWZZVXE0Tm5LYm9TdXk0Ckt4RDFCbkQvK2M0N1AyZ1Zyczdj
            b084cEVuRWsyc3FHMXhYMjROb2JpdTAKLS0tIGRKdXdWcWRFeTRjQllFZjJpWHZ3
            UzJINy9SWW84VGM2RVVxWlJ3TG5ra0UKWKDZbc0xeYZFqCSfycJonXvAd3YNQHfy
            f3S9U44Wp3grUUqhtLPj3TjnpwBr7lVvlnePhdhk7jHcgabc/6CRZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T18:36:30Z"
    mac: ENC[AES256_GCM,data:JOn3MHaAx2Ps9fhQV6LZlb1Z/nkJbzcL++MBulb4rSeepD7YiJSGWhbxP6wACzGelgy+0AN3u4jOHjaEpD4IIxxGmQ4+8gPfM9tWUumtyF6jLllr/U7tRzMl332xQbV8apU8Z5GhPLv6yyQ50+BbzBqrlBvaYQZPGoLzg3+U6vQ=,iv:gfnO/muSjEbRrcLeBUnsEh97mIq1GgtlFVX1mouGK04=,tag:mDwgNRiH8ssnS2f5Hj/dyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
