apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:/D/tPfbOvR4wk6ag2U1Ldrg1rh65hM08vt4kvd4GEv3lIvCOSCZImg==,iv:3pBdMfKnfvO4ffRSG8Yywv6eevHa0hq8bs0toNahidg=,tag:Lnot/EHQFWeqivFxPPRG4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qp9m08g8trwxn5a40c2p8dnweem68djtdzukg2q4tfy5qlun7pwshxjuxw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicXJaWTZnSmt4cmdkZE1I
            R0lMMzZVVFBpQlloVWFTWUZiN0lZa1RTUnpRCkVDQXdja1lDYVNLbWVNQ0hxUUVU
            OUxmamRneFI3WHNYeEk4Y3Z4Z09FcjAKLS0tIE80TnVYWDdPNmhPTjdZVlU1UG9Y
            T3gyMlRRS1gwZDBoMzA3TkZ4a1BMY1EKTZEvZRDFhlI9te9iZWNwCIQ+0GtnCDCw
            34UQ7Xtydyho75otRV/QaDeqWlOYgpsEbaKVU5NHXmbEVqBEYw+1wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T18:15:35Z"
    mac: ENC[AES256_GCM,data:jKKDFNhsUodY1IezqKxIYbveMm8QxyMl4TQjYD65hyMmUxiGRy/5vceLZJc1iSv0fRQObzYcneqN9QJL7X8mTcTvZ9qsnsl/24xve3PoPnj4Fm9gaorthoxac5vJ2as2WLHeis1wcK6428KzBLTkv0qoL7R+gPByFFoQrOtJQp4=,iv:nMjoK2D6RwnzQ31JQb+nvazYq3kPEMKJEkxnzBrLAGw=,tag:ge0e6GxQaLRlPVJYUuEHcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
